# Generated by Django 6.0 on 2026-01-13 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.URLField(blank=True, max_length=255, null=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('cupcake', 'Cupcake'), ('bumblebee', 'Bumblebee'), ('emerald', 'Emerald'), ('corporate', 'Corporate'), ('synthwave', 'Synthwave'), ('retro', 'Retro'), ('cyberpunk', 'Cyberpunk'), ('valentine', 'Valentine'), ('halloween', 'Halloween'), ('garden', 'Garden'), ('forest', 'Forest'), ('aqua', 'Aqua'), ('lofi', 'Lofi'), ('pastel', 'Pastel'), ('fantasy', 'Fantasy'), ('wireframe', 'Wireframe'), ('black', 'Black'), ('luxury', 'Luxury'), ('dracula', 'Dracula'), ('cmyk', 'Cmyk'), ('autumn', 'Autumn'), ('business', 'Business'), ('acid', 'Acid'), ('lemonade', 'Lemonade'), ('night', 'Night'), ('coffee', 'Coffee'), ('winter', 'Winter'), ('dim', 'Dim'), ('nord', 'Nord'), ('sunset', 'Sunset'), ('caramellatte', 'Caramellatte'), ('abyss', 'Abyss'), ('silk', 'Silk')], default='light', max_length=255)),
                ('content', models.JSONField(blank=True, null=True)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('policies', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('images', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(choices=[('usd', 'Usd'), ('cad', 'Cad')], default='usd', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='shops.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product'], name='shops_price_product_32def6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['slug'], name='shops_shop_slug_f77e23_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['user'], name='shops_shop_user_id_149b18_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop'], name='shops_produ_shop_id_2cd91f_idx'),
        ),
    ]
