import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "../stores/cartStore";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light" data-color-mode="false">
      <body className="antialiased bg-base-100">
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
