# Generated by Django 6.0 on 2026-01-01 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_amount', models.IntegerField()),
                ('currency', models.CharField(choices=[('usd', 'Usd'), ('cad', 'Cad')], default='usd', max_length=3)),
                ('interval', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='identity_pl_code_6ffe66_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_start_date', models.DateTimeField(blank=True, null=True)),
                ('plan_end_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('card', 'Card')], default='card', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='identity.plan')),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='identity_us_id_ed7e65_idx'), models.Index(fields=['email'], name='identity_us_email_bcdd3b_idx')],
            },
        ),
    ]
