# Generated by Django 6.0 on 2026-01-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_alter_plan_currency_alter_plan_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='administrative_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(choices=[('usd', 'Usd'), ('cad', 'Cad')], default='usd', max_length=3),
        ),
        migrations.AlterField(
            model_name='plan',
            name='interval',
            field=models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=255),
        ),
    ]
