# Generated by Django 6.0 on 2026-01-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_alter_plan_code_alter_plan_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(choices=[('usd', 'Usd'), ('cad', 'Cad')], default='usd', max_length=3),
        ),
        migrations.AlterField(
            model_name='plan',
            name='interval',
            field=models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=255),
        ),
    ]
